# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


@pytest.fixture()
def start_date():
    return "20190102"

@pytest.fixture
def end_date():
    return '20190302'
  
@pytest.fixture()
def amount():
    return 310

class Test():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_set_budget(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1260, 689)
    self.driver.find_element(By.NAME, "Date").click()
    self.driver.find_element(By.NAME, "Date").send_keys("20190102")
    self.driver.find_element(By.NAME, "Amount").click()
    self.driver.find_element(By.NAME, "Amount").send_keys("5000")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "body").text == "Create Success"
  
  def test_query_budget(self, start_date, end_date, amount):
    db.reset_budget_table()
    db.insert_budget(date[:6], 31)

    self.driver.get("http://127.0.0.1:5000/query")
    self.driver.set_window_size(1260, 689)
    self.driver.find_element(By.NAME, "start_date").click()
    self.driver.find_element(By.NAME, "start_date").send_keys(start_date)
    self.driver.find_element(By.NAME, "end_date").click()
    self.driver.find_element(By.NAME, "end_date").send_keys(end_date)
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "body").text == f"Query budget {start_date}: {end_date} successfully"
    
    # wait module

  
